; MahlanyaRPG — DefaultInput.ini
[/Script/Engine.InputSettings]
+ConsoleKeys=F10
+ConsoleKeys=Tilde

+DebugExecBindings=(Key=F11,Command="stat mahlanyasim",Control=False,Shift=False,Alt=False)
+DebugExecBindings=(Key=F12,Command="stat simulationtrust",Control=False,Shift=False,Alt=False)
+DebugExecBindings=(Key=F9,Command="TogglePerformanceMonitor",Control=False,Shift=False,Alt=True)
